name: CI

on: [ push, pull_request, release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install mtools
      run: sudo apt-get install mtools
    - name: Build GNU EFI
      run: make -C ./bootloader/gnu-efi
    - name: Build bootloader
      run: make -C ./bootloader
    - name: Setup directories
      run: make -C ./kernel setup
    - name: Build kernel
      run: make -C ./kernel
    - name: Build image
      run: make -C ./kernel buildimg
    - name: Upload kernel.elf
      uses: actions/upload-artifact@v2
      with:
        name: kernel.elf
        path: kernel/bin/kernel.elf
    - name: Upload corruptOS.img
      uses: actions/upload-artifact@v2
      with:
        name: corruptOS.img
        path: kernel/bin/corruptOS.img
